#!/bin/bash

echo "╔══════════════════════════════════════╗"
echo "║    Siri Shortcut — Hey Siri Chief    ║"
echo "╚══════════════════════════════════════╝"
echo ""
echo "To set up 'Hey Siri, Chief':"
echo ""
echo "1. Open the Shortcuts app on your iPhone"
echo "2. Tap + to create a new shortcut"
echo "3. Add action: 'Open URLs'"
echo "4. Set URL to: https://chiefcommand.app/voice"
echo "5. Tap the shortcut name at the top"
echo "6. Rename it to: Chief"
echo "7. Done! Say 'Hey Siri, Chief' to launch"
echo ""
echo "For auto-mic activation, the PWA will detect"
echo "the ?auto=1 URL param and start listening."
echo "Update the shortcut URL to:"
echo "  https://chiefcommand.app/voice?auto=1"
echo ""
